spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        prefix: config
    refresh:
      # todo: try without this property
      enabled: false
  data:
    redis:
#      cluster:
#        nodes: redis-cluster:6379

#      host: redis-cluster
      host: localhost
      port: 6379
  profiles:
    default: dev
    group:
      dev:
        - redis
  kafka:
#    bootstrap-servers: kafka-container:9092
    bootstrap-servers: localhost:9092


# todo: remove this property
server:
  port: 7999
