# base from tomcat:10.1
FROM tomcat:10.1
# copy target/{created_artifact}.war to /usr/local/tomcat/webapps/{servlet_name}.war
COPY target/servlet-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/my_servlet.war
