spring:
  config:
    import: optional:configserver:http://localhost:8888/config
  datasource:
    url: jdbc:postgresql://localhost:5432/shopping
    username: student
  kafka:
    bootstrap-servers: localhost:9092
